### ISSUE TITLE
Erro na revalidação da sessão do usuário

### ISSUE THREAD

**Issue by guerreiro0207** [fabiojaniolima/laraboot#2]
O erro ocorre quando o usuário vence o tempo da sessão, isso não ocorre se a opção **Lembrar-me** estiver sido marcada.

Erro: `Class 'App\Http\Middleware\AuthenticationException' not found`.

**Comment by fabiojaniolima** [comment]
Identifiquei que este erro está ocorrendo pois não realizei o import de `Illuminate\Auth\AuthenticationException` ao sobrescrever o método `authenticate`.

Erro introduzido no comia: [751cf6f](https://github.com/fabiojaniolima/laraboot/commit/751cf6f33242c8fbc7e9a0bb06dda4931836c667). Efetuando correção.
